import { useState } from 'react';
import { Search, FileText, Volume2 } from 'lucide-react';
import { useSession } from '../../context/SessionContext';
import { speak } from '../../lib/speech';
export function TranscriptFeedScreen() {
  const { transcript, selectedLang } = useSession();
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState('all');
  const items = transcript.filter(item => (filter === 'all' || item.speaker === filter) && `${item.text} ${item.textEn || ''}`.toLowerCase().includes(query.toLowerCase().trim()));
  return <main><div className="mx-auto px-4 sm:px-6 lg:px-8 flex flex-col gap-6">
    <div className="flex items-center justify-between"><div><span className="eyebrow-label">Conversation history</span><h1 className="text-display-md font-bold mt-2">Session transcript</h1><p className="text-secondary mt-3">Review messages from both sides of the conversation.</p></div><a href="#summary" className="secondary-action">Review summary</a></div>
    <section className="content-card flex flex-col gap-5"><div className="flex flex-wrap gap-4 items-center justify-between"><div className="flex items-center gap-3 border border-outline-variant rounded-xl px-4 py-3 w-full sm:w-96"><Search size={20} className="text-secondary shrink-0"/><label className="sr-only" htmlFor="transcript-search">Search transcript</label><input id="transcript-search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search messages…" className="w-full bg-transparent outline-none"/></div><div className="flex flex-wrap gap-2" role="group" aria-label="Filter by speaker">{['all', 'doctor', 'patient'].map(value => <button key={value} aria-pressed={filter === value} className={filter === value ? 'primary-action' : 'secondary-action'} onClick={() => setFilter(value)}>{value === 'all' ? 'All messages' : value === 'doctor' ? 'Doctor' : 'Patient'}</button>)}</div></div><p className="text-label-md text-secondary" role="status">{items.length} {items.length === 1 ? 'message' : 'messages'}</p></section>
    {items.length ? <ol className="flex flex-col gap-4">{items.map(item => <li className="content-card" key={item.id}><div className="flex items-center justify-between mb-3"><span className="text-label-md text-primary font-semibold capitalize">{item.speaker}</span><time className="text-label-sm text-secondary">{item.timestamp}</time></div><p className="text-body-xl leading-relaxed">{item.text}</p>{item.textEn && item.textEn !== item.text && <p className="text-secondary mt-2">{item.textEn}</p>}<button className="secondary-action mt-4" onClick={() => speak(item.text, selectedLang)} aria-label={`Read ${item.speaker} message aloud`}><Volume2 size={16}/>Read aloud</button></li>)}</ol> : <section className="content-card empty-state"><FileText size={36} className="mx-auto mb-4"/><h2 className="text-headline-md font-semibold">{transcript.length ? 'No matching messages' : 'Your conversation starts here'}</h2><p className="mt-2">{transcript.length ? 'Try another search or choose all messages.' : 'Messages will appear here as you use the consultation.'}</p>{transcript.length ? <button className="secondary-action mt-5" onClick={() => {setQuery(''); setFilter('all');}}>Clear filters</button> : <a href="#bridge" className="primary-action mt-5">Start a conversation</a>}</section>}
  </div></main>;
}
